#!/usr/bin/env python
"""
Copyright 2014 Jirafe, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class OrderItem:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'id': 'str',
            'create_date': 'datetime',
            'change_date': 'datetime',
            'order_item_number': 'str',
            'quantity': 'integer',
            'status': '',
            'price': 'number',
            'discount_price': 'number',
            'product': 'Product'

        }


        self.id = None # str
        self.create_date = None # datetime
        self.change_date = None # datetime
        self.order_item_number = None # str
        self.quantity = None # integer
        self.status = None # 
        self.price = None # number
        self.discount_price = None # number
        self.product = None # Product
        
