#!/usr/bin/env python
"""
Copyright 2014 Jirafe, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

from models import *


class CategoryApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    def postCategory(self, siteId, body, **kwargs):
        """Send a category for the given site

        Args:
            siteId, str: ID site to send the event (required)
            body, Category: category json for the event (required)
            
        Returns: 
        """

        allParams = ['siteId', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method postCategory" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/{siteId}/category'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}

        if ('siteId' in params):
            replacement = str(self.apiClient.toPathValue(params['siteId']))
            resourcePath = resourcePath.replace('{' + 'siteId' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        
        
    


